// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/core/controllers/health_checks_controller.ts').default['handle'], false>
}
type LoginGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/login_controller.ts').default['show'], false>
}
type LoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/validator.js')['loginSchema']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/login_controller.ts').default['handle'], true>
}
type RegisterGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/register_controller.ts').default['show'], false>
}
type RegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/validator.js')['registerValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/register_controller.ts').default['handle'], true>
}
type ForgotPasswordGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/forgot_password_controller.ts').default['show'], false>
}
type ForgotPasswordPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/validator.js')['forgotPasswordSchema']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/forgot_password_controller.ts').default['handle'], true>
}
type ResetpasswordIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/reset_password_controller.ts').default['show'], false>
}
type ResetpasswordIdPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/validator.js')['resetPasswordSchema']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/reset_password_controller.ts').default['handle'], true>
}
type AuthGoogleRedirectGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/social_controller.ts').default['redirect'], false>
}
type AuthGoogleCallbackGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/social_controller.ts').default['callback'], false>
}
type LogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/logout_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
  'login': {
    '$url': {
    };
    '$get': LoginGetHead;
    '$head': LoginGetHead;
    '$post': LoginPost;
  };
  'register': {
    '$url': {
    };
    '$get': RegisterGetHead;
    '$head': RegisterGetHead;
    '$post': RegisterPost;
  };
  'forgot-password': {
    '$url': {
    };
    '$get': ForgotPasswordGetHead;
    '$head': ForgotPasswordGetHead;
    '$post': ForgotPasswordPost;
  };
  'reset-password': {
    ':token': {
      '$url': {
      };
      '$get': ResetpasswordIdGetHead;
      '$head': ResetpasswordIdGetHead;
      '$post': ResetpasswordIdPost;
    };
  };
  'auth': {
    'google': {
      'redirect': {
        '$url': {
        };
        '$get': AuthGoogleRedirectGetHead;
        '$head': AuthGoogleRedirectGetHead;
      };
      'callback': {
        '$url': {
        };
        '$get': AuthGoogleCallbackGetHead;
        '$head': AuthGoogleCallbackGetHead;
      };
    };
  };
  'logout': {
    '$url': {
    };
    '$post': LogoutPost;
  };
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/uploads/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'login.show',
    path: '/login',
    method: ["GET","HEAD"],
    types: {} as LoginGetHead,
  },
  {
    params: [],
    name: 'login.handle',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'register.show',
    path: '/register',
    method: ["GET","HEAD"],
    types: {} as RegisterGetHead,
  },
  {
    params: [],
    name: 'register.handle',
    path: '/register',
    method: ["POST"],
    types: {} as RegisterPost,
  },
  {
    params: [],
    name: 'forgot_password.show',
    path: '/forgot-password',
    method: ["GET","HEAD"],
    types: {} as ForgotPasswordGetHead,
  },
  {
    params: [],
    name: 'forgot_password.handle',
    path: '/forgot-password',
    method: ["POST"],
    types: {} as ForgotPasswordPost,
  },
  {
    params: ["token"],
    name: 'reset_password.show',
    path: '/reset-password/:token',
    method: ["GET","HEAD"],
    types: {} as ResetpasswordIdGetHead,
  },
  {
    params: ["token"],
    name: 'reset_password.handle',
    path: '/reset-password/:token',
    method: ["POST"],
    types: {} as ResetpasswordIdPost,
  },
  {
    params: [],
    name: 'social.show',
    path: '/auth/google/redirect',
    method: ["GET","HEAD"],
    types: {} as AuthGoogleRedirectGetHead,
  },
  {
    params: [],
    name: 'social.callback',
    path: '/auth/google/callback',
    method: ["GET","HEAD"],
    types: {} as AuthGoogleCallbackGetHead,
  },
  {
    params: [],
    name: 'logout.handle',
    path: '/logout',
    method: ["POST"],
    types: {} as LogoutPost,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
declare module '@tuyau/inertia/types' {
  type InertiaApi = typeof api
  export interface Api extends InertiaApi {}
}
