enum BookingActions {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
  CHECK = 'CHECK',
  ATTEMPT_PICKUP = 'ATTEMPT_PICKUP',
  ATTEMPT_DELIVERY = 'ATTEMPT_DELIVERY',
  ATTEMPT_CHECK = 'ATTEMPT_CHECK',
  RELEASE_PICKUP = 'RELEASE_PICKUP',
  RELEASE_DELIVERY = 'RELEASE_DELIVERY',
  RELEASE_CHECK = 'RELEASE_CHECK',
}

export default BookingActions
